### ISSUE TITLE
Type definition changes in 1.3.12 break usage with `extends`

### ISSUE THREAD

**Issue by haines** [vitest-dev/eslint-plugin-vitest#761]
We have our config defined as follows:

```typescript
import vitestPlugin from "@vitest/eslint-plugin";
import { defineConfig } from "eslint/config";

export const vitestConfig = defineConfig({
  files: ["**/*.test.ts"],
  extends: [vitestPlugin.configs.recommended],
  settings: {
    vitest: {
      typecheck: true,
    },
  }
});
```

This worked in v1.3.10 but breaks in 1.3.12:

```
eslint-plugin-vitest.ts:6:13 - error TS2322: Type '{ readonly name: "vitest/recommended"; readonly plugins: { readonly vitest: { readonly meta: { readonly name: "vitest"; readonly version: string; }; readonly rules: { readonly "prefer-lowercase-title": RuleModule<MessageIds, [...], PluginDocs, RuleListener>; ... 71 more ...; readonly "warn-todo": RuleModule<...>; };...' is not assignable to type 'ExtendsElement'.
  Type '{ readonly name: "vitest/recommended"; readonly plugins: { readonly vitest: { readonly meta: { readonly name: "vitest"; readonly version: string; }; readonly rules: { readonly "prefer-lowercase-title": RuleModule<MessageIds, [...], PluginDocs, RuleListener>; ... 71 more ...; readonly "warn-todo": RuleModule<...>; };...' is not assignable to type 'Config<RulesRecord>'.
    Types of property 'plugins' are incompatible.
      Type '{ readonly vitest: { readonly meta: { readonly name: "vitest"; readonly version: string; }; readonly rules: { readonly "prefer-lowercase-title": RuleModule<MessageIds, [Partial<{ ignore: string[]; allowedPrefixes: string[]; ignoreTopLevelDescribe: boolean; lowercaseFirstCharacterOnly: boolean; }>], PluginDocs, RuleL...' is not assignable to type 'Record<string, Plugin>'.
        Property 'vitest' is incompatible with index signature.
          Type '{ readonly meta: { readonly name: "vitest"; readonly version: string; }; readonly rules: { readonly "prefer-lowercase-title": RuleModule<MessageIds, [Partial<{ ignore: string[]; allowedPrefixes: string[]; ignoreTopLevelDescribe: boolean; lowercaseFirstCharacterOnly: boolean; }>], PluginDocs, RuleListener>; ... 71 mo...' is not assignable to type 'Plugin'.
            Types of property 'rules' are incompatible.
              Type '{ readonly "prefer-lowercase-title": RuleModule<MessageIds, [Partial<{ ignore: string[]; allowedPrefixes: string[]; ignoreTopLevelDescribe: boolean; lowercaseFirstCharacterOnly: boolean; }>], PluginDocs, RuleListener>; ... 71 more ...; readonly "warn-todo": RuleModule<...>; }' is not assignable to type 'Record<string, RuleDefinition<RuleDefinitionTypeOptions>>'.
                Property '"prefer-lowercase-title"' is incompatible with index signature.
                  Type 'RuleModule<MessageIds, [Partial<{ ignore: string[]; allowedPrefixes: string[]; ignoreTopLevelDescribe: boolean; lowercaseFirstCharacterOnly: boolean; }>], PluginDocs, RuleListener>' is not assignable to type 'RuleDefinition<RuleDefinitionTypeOptions>'.
                    Types of property 'create' are incompatible.
                      Type '(context: Readonly<RuleContext<MessageIds, [Partial<{ ignore: string[]; allowedPrefixes: string[]; ignoreTopLevelDescribe: boolean; lowercaseFirstCharacterOnly: boolean; }>]>>) => RuleListener' is not assignable to type '(context: RuleContext<{ LangOptions: LanguageOptions; Code: SourceCode<{ LangOptions: LanguageOptions; RootNode: unknown; SyntaxElementWithLoc: unknown; ConfigNode: unknown; }>; RuleOptions: unknown[]; Node: unknown; MessageIds: string; }>) => RuleVisitor'.
                        Types of parameters 'context' and 'context' are incompatible.
                          Type 'RuleContext<{ LangOptions: LanguageOptions; Code: SourceCode<{ LangOptions: LanguageOptions; RootNode: unknown; SyntaxElementWithLoc: unknown; ConfigNode: unknown; }>; RuleOptions: unknown[]; Node: unknown; MessageIds: string; }>' is missing the following properties from type 'Readonly<RuleContext<MessageIds, [Partial<{ ignore: string[]; allowedPrefixes: string[]; ignoreTopLevelDescribe: boolean; lowercaseFirstCharacterOnly: boolean; }>]>>': getAncestors, getDeclaredVariables, getScope, markVariableAsUsed

6   extends: [vitestPlugin.configs.recommended],
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error.
```

I believe the addition of `readonly` to all the properties has caused this incompatibility?

Repro: https://github.com/haines/eslint-plugin-vitest-types
